#!/usr/bin/env python3
"""
Generate clamp_improved_{red,green,blue}[512]: for each 9-bit CLAMP dot pattern,
output the R,G,B TMDS values from the nearest improved IIgs LORES color.
Uses Euclidean distance in sRGB space for perceptual match.
Precomputed LUT avoids flash reads in the scanline loop; same 3-lookup cost as
the original 8to3 path.
"""
import re
import sys
import math

# Improved IIgs palette: (TMDS for output, sRGB for matching) - LoresRgb2 from tmdsLores.py
IMPROVED_TMDS = [
    (0x7fd00, 0x7fd00, 0x7fd00),  # 0 black
    (0xb8e1c, 0x97ea0, 0x7053e),  # 1 magenta
    (0x7ed04, 0x7c10f, 0x58d9c),  # 2 darkblue
    (0x87ae1, 0x4f9c1, 0x6815f),  # 3 purple
    (0x42df4, 0x6057e, 0x441ef),  # 4 darkgreen
    (0x77921, 0x77921, 0x77921),  # 5 gray1
    (0x7a117, 0x906be, 0xbfe00),  # 6 mediumblue
    (0x9f283, 0x8eec4, 0xbfe00),  # 7 lightblue
    (0x5c18f, 0x48ddc, 0x7fd00),  # 8 brown
    (0xbf203, 0xa1e78, 0x7fd00),  # 9 orange
    (0x8eec4, 0x8eec4, 0x8eec4),  # 10 gray2
    (0x80efc, 0x67163, 0x63971),  # 11 pink
    (0x4fdc0, 0xb821f, 0x7fd00),  # 12 green
    (0x802ff, 0x802ff, 0x7fd00),  # 13 yellow
    (0x9de88, 0xbfa01, 0x67961),  # 14 aqua
    (0xbfe00, 0xbfe00, 0xbfe00),  # 15 white
]
IMPROVED_SRGB = [
    (0x00, 0x00, 0x00), (0x9d, 0x09, 0x66), (0x2a, 0x2a, 0xe5), (0xc7, 0x34, 0xff),
    (0x00, 0x80, 0x00), (0x80, 0x80, 0x80), (0x0d, 0xa1, 0xff), (0xaa, 0xaa, 0xff),
    (0x55, 0x55, 0x00), (0xf2, 0x5e, 0x00), (0xC0, 0xC0, 0xC0), (0xff, 0x89, 0xe5),
    (0x38, 0xcb, 0x00), (0xd5, 0xd5, 0x1a), (0x62, 0xf6, 0x99), (0xff, 0xff, 0xff),
]


def tmds_to_srgb(val):
    """TMDS (~0x40000-0xbfe00) to sRGB 0-255. Heuristic linear scale."""
    v = max(0, min(0xFFFFF, val & 0xFFFFF))
    return max(0, min(255, int((v - 0x40000) * 255 / (0xbfe00 - 0x40000))))


def parse_hex_array(path, max_count=None):
    with open(path) as f:
        text = f.read()
    vals = [int(m, 16) for m in re.findall(r"0x[0-9a-fA-F]+", text)]
    if max_count is not None:
        vals = vals[:max_count]
    return vals


def main():
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    lut_dir = base + "/firmware/a2c"
    header = lut_dir + "/hgrdecode_LUT.h"
    # Header order: 8to3_red[512], clamp_improved_red[512], clamp_improved_green[512],
    #               clamp_improved_blue[512], 8to3_green[512], 8to3_blue[512]
    all_hex = parse_hex_array(header, 3072)
    clamp_r = all_hex[0:512]
    clamp_g = all_hex[2048:2560]   # 8to3 green (after clamp_improved)
    clamp_b = all_hex[2560:3072]   # 8to3 blue

    # Phase-invariant: oddness bit (0x100) alternates every 8 pixels. To avoid striations,
    # both phases (i and i^0x100) must map to the same improved color. Use averaged
    # sRGB of both 8to3 outputs to pick one consistent color per base pattern.
    out_r, out_g, out_b = [], [], []
    for i in range(512):
        i_other = i ^ 0x100  # phase pair
        sr1 = tmds_to_srgb(clamp_r[i])
        sg1 = tmds_to_srgb(clamp_g[i])
        sb1 = tmds_to_srgb(clamp_b[i])
        sr2 = tmds_to_srgb(clamp_r[i_other])
        sg2 = tmds_to_srgb(clamp_g[i_other])
        sb2 = tmds_to_srgb(clamp_b[i_other])
        sr = (sr1 + sr2) / 2
        sg = (sg1 + sg2) / 2
        sb = (sb1 + sb2) / 2
        best_j = 0
        best_d = float("inf")
        for j, (ir, ig, ib) in enumerate(IMPROVED_SRGB):
            d = math.sqrt((sr - ir) ** 2 + (sg - ig) ** 2 + (sb - ib) ** 2)
            if d < best_d:
                best_d = d
                best_j = j
        ir, ig, ib = IMPROVED_TMDS[best_j]
        out_r.append(ir)
        out_g.append(ig)
        out_b.append(ib)

    def fmt_row(arr, start):
        return ", ".join(f"0x{arr[start + k]:05X}" for k in range(16))

    print("// Generated by tools/clamp_improved_lut.py")
    print("// RM_CLAMP: precomputed R,G,B from nearest improved IIgs LORES color (sRGB match).")
    print("// Same 3-lookup path as 8to3; all in RAM, no flash reads.")
    print("")
    print("uint32_t DELAYED_COPY_DATA(clamp_improved_red)[512] = {")
    for i in range(0, 512, 16):
        print(f"    {fmt_row(out_r, i)},")
    print("};")
    print("")
    print("uint32_t DELAYED_COPY_DATA(clamp_improved_green)[512] = {")
    for i in range(0, 512, 16):
        print(f"    {fmt_row(out_g, i)},")
    print("};")
    print("")
    print("uint32_t DELAYED_COPY_DATA(clamp_improved_blue)[512] = {")
    for i in range(0, 512, 16):
        print(f"    {fmt_row(out_b, i)},")
    print("};")


if __name__ == "__main__":
    main()
