#!/usr/bin/env python3
"""
Generate clamp_improved_{red,green,blue}[512]: for each 9-bit CLAMP dot pattern,
output the R,G,B TMDS values from the nearest improved IIgs LORES color.
Uses weighted L2 distance in TMDS space (green weighted 2x for perceptual match).
Precomputed LUT avoids flash reads in the scanline loop; same 3-lookup cost as
the original 8to3 path.
"""
import re
import sys
import math

# Improved IIgs palette from tmds_lores.c (tmds_lores_improved), 16 colors x 3 (R,G,B)
IMPROVED = [
    (0x7fd00, 0x7fd00, 0x7fd00),  # black
    (0xb8e1c, 0x97ea0, 0x7053e),  # magenta
    (0x7ed04, 0x7c10f, 0x58d9c),  # darkblue
    (0x87ae1, 0x4f9c1, 0x6815f),  # purple
    (0x42df4, 0x6057e, 0x441ef),  # darkgreen
    (0x77921, 0x77921, 0x77921),  # gray1
    (0x7a117, 0x906be, 0xbfe00),  # mediumblue
    (0x9f283, 0x8eec4, 0xbfe00),  # lightblue
    (0x5c18f, 0x48ddc, 0x7fd00),  # brown
    (0xbf203, 0xa1e78, 0x7fd00),  # orange
    (0x8eec4, 0x8eec4, 0x8eec4),  # gray2
    (0x80efc, 0x67163, 0x63971),  # pink
    (0x4fdc0, 0xb821f, 0x7fd00),  # green
    (0x802ff, 0x802ff, 0x7fd00),  # yellow
    (0x9de88, 0xbfa01, 0x67961),  # aqua
    (0xbfe00, 0xbfe00, 0xbfe00),  # white
]


def parse_hex_array(path, max_count=None):
    with open(path) as f:
        text = f.read()
    vals = [int(m, 16) for m in re.findall(r"0x[0-9a-fA-F]+", text)]
    if max_count is not None:
        vals = vals[:max_count]
    return vals


def weighted_l2(r, g, b, ir, ig, ib, wg=2.0):
    """Weighted L2; green weighted for better perceptual match."""
    return math.sqrt((r - ir) ** 2 + wg * (g - ig) ** 2 + (b - ib) ** 2)


def main():
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    lut_dir = base + "/firmware/a2c"
    header = lut_dir + "/hgrdecode_LUT.h"
    # First three arrays in header: red[512], green[512], blue[512]
    all_hex = parse_hex_array(header, 512 * 3)
    clamp_r = all_hex[0:512]
    clamp_g = all_hex[512:1024]
    clamp_b = all_hex[1024:1536]

    out_r, out_g, out_b = [], [], []
    for i in range(512):
        r, g, b = clamp_r[i], clamp_g[i], clamp_b[i]
        best_j = 0
        best_d = float("inf")
        for j, (ir, ig, ib) in enumerate(IMPROVED):
            d = weighted_l2(r, g, b, ir, ig, ib)
            if d < best_d:
                best_d = d
                best_j = j
        ir, ig, ib = IMPROVED[best_j]
        out_r.append(ir)
        out_g.append(ig)
        out_b.append(ib)

    def fmt_row(arr, start):
        return ", ".join(f"0x{arr[start + k]:05X}" for k in range(16))

    print("// Generated by tools/clamp_improved_lut.py")
    print("// RM_CLAMP: precomputed R,G,B from nearest improved IIgs LORES color.")
    print("// Same 3-lookup path as 8to3; all in RAM, no flash reads.")
    print("")
    print("uint32_t DELAYED_COPY_DATA(clamp_improved_red)[512] = {")
    for i in range(0, 512, 16):
        print(f"    {fmt_row(out_r, i)},")
    print("};")
    print("")
    print("uint32_t DELAYED_COPY_DATA(clamp_improved_green)[512] = {")
    for i in range(0, 512, 16):
        print(f"    {fmt_row(out_g, i)},")
    print("};")
    print("")
    print("uint32_t DELAYED_COPY_DATA(clamp_improved_blue)[512] = {")
    for i in range(0, 512, 16):
        print(f"    {fmt_row(out_b, i)},")
    print("};")


if __name__ == "__main__":
    main()
