#!/usr/bin/env python3
"""
Generate clamp_to_improved_index[512]: for each 9-bit CLAMP LUT pattern,
output the index (0-15) of the nearest improved IIgs LORES color.
Uses L1 distance in TMDS symbol space.
"""
import re
import sys

# Improved IIgs palette from tmds_lores.c (tmds_lores_improved), 16 colors x 3 (R,G,B)
IMPROVED = [
    (0x7fd00, 0x7fd00, 0x7fd00),  # black
    (0xb8e1c, 0x97ea0, 0x7053e),  # magenta
    (0x7ed04, 0x7c10f, 0x58d9c),  # darkblue
    (0x87ae1, 0x4f9c1, 0x6815f),  # purple
    (0x42df4, 0x6057e, 0x441ef),  # darkgreen
    (0x77921, 0x77921, 0x77921),  # gray1
    (0x7a117, 0x906be, 0xbfe00),  # mediumblue
    (0x9f283, 0x8eec4, 0xbfe00),  # lightblue
    (0x5c18f, 0x48ddc, 0x7fd00),  # brown
    (0xbf203, 0xa1e78, 0x7fd00),  # orange
    (0x8eec4, 0x8eec4, 0x8eec4),  # gray2
    (0x80efc, 0x67163, 0x63971),  # pink
    (0x4fdc0, 0xb821f, 0x7fd00),  # green
    (0x802ff, 0x802ff, 0x7fd00),  # yellow
    (0x9de88, 0xbfa01, 0x67961),  # aqua
    (0xbfe00, 0xbfe00, 0xbfe00),  # white
]


def parse_hex_array(path, max_count=None):
    with open(path) as f:
        text = f.read()
    vals = [int(m, 16) for m in re.findall(r"0x[0-9a-fA-F]+", text)]
    if max_count is not None:
        vals = vals[:max_count]
    return vals


def main():
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    lut_dir = base + "/firmware/a2c"
    header = lut_dir + "/hgrdecode_LUT.h"
    # First three arrays in header are clamp 8to3 LUT: red[512], green[512], blue[512]
    all_hex = parse_hex_array(header, 512 * 3)
    clamp_r = all_hex[0:512]
    clamp_g = all_hex[512:1024]
    clamp_b = all_hex[1024:1536]

    index_table = []
    for i in range(512):
        r, g, b = clamp_r[i], clamp_g[i], clamp_b[i]
        best_j = 0
        best_d = float("inf")
        for j, (ir, ig, ib) in enumerate(IMPROVED):
            d = abs(r - ir) + abs(g - ig) + abs(b - ib)
            if d < best_d:
                best_d = d
                best_j = j
        index_table.append(best_j)

    # Print C array
    print("// Generated by tools/clamp_to_improved_lut.py")
    print("// Maps 9-bit CLAMP dot pattern -> tmds_lores_improved index (0-15)")
    print("static const uint8_t clamp_to_improved_index[512] = {")
    for i in range(0, 512, 16):
        row = ", ".join(str(index_table[i + k]) for k in range(16))
        print(f"    {row},")
    print("};")


if __name__ == "__main__":
    main()
